### ISSUE TITLE
Merge alexheretic/atom-languageclient/tree/build to support ide-rust

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-languageclient#156]
We need to merge the changes by @alexheretic from this branch, so ide-rust can switch to our fork
~https://github.com/alexheretic/atom-languageclient/tree/build~
https://github.com/atom-community/atom-languageclient/tree/ide-rust-build-no-rebuild (cleaned version)

- [x] [definitions for out-of-project files](https://github.com/atom-community/atom-languageclient/commit/6188c19888f285c42986764a569567a2df47e7cf) -> #160 
- [x] [Add shutdownServersGracefully() config function](https://github.com/atom-community/atom-languageclient/commit/11793871a00a8329bb53e1270d931768f70cd7d4) -> #161
- [x] [Fix completion deleting the triggerChar](https://github.com/atom-community/atom-languageclient/commit/0dcdd696b865ad72f0efcdb2a628b33d668dbee2) - already fixed in #114 
- [x] [Implement completion additionalTextEdits](https://github.com/atom-community/atom-languageclient/commit/1df5bd582e4109002771c42ed24de2197a6b0488) -> #162
- [x] [Support non-boolean *Provider server capabilities](https://github.com/atom-community/atom-languageclient/commit/5319279d68cf8837bc46cdf62975886c6b79052b) -> Already fixed
- [x] [send codeActionLiteralSupport](https://github.com/atom-community/atom-languageclient/commit/d5004ed2a159d165d2bf438161e9717f69b1c6c2) -> #167
- [x] [Support custom filterCodeActions & onApplyCodeActions](https://github.com/atom-community/atom-languageclient/commit/3ea785781ac299e4a0f5d4500bc5aedcb15399bf) -> #167

Allows fixing https://github.com/rust-lang/atom-ide-rust/issues/175

**Comment by aminya** [comment]
I created a branch here:
https://github.com/atom-community/atom-languageclient/tree/ide-rust-build
